FROM golang:latest as builder

COPY . /srv/rack

RUN cd /srv/rack &&\
    make docker-in &&\
    ls -l bin


FROM alpine:latest

LABEL source.url="https://github.com/fimreal/rack"

COPY --from=builder /srv/rack/bin/rack /rack

CMD [ "/rack" ]

RUN apk add --no-cache tzdata &&\
    cp /usr/share/zoneinfo/Asia/Shanghai /etc/localtime &&\
    echo "Asia/Shanghai" > /etc/timezone