#!/bin/env sh

case "$1" in
	aliyun)
		ALPINE_REPO="mirrors.aliyun.com"
		;;
	ustc)
		ALPINE_REPO="mirrors.ustc.edu.cn"
		;;
	tuna)
		ALPINE_REPO="mirror.tuna.tsinghua.edu.cn"
		;;
  *)
		ALPINE_REPO="dl-cdn.alpinelinux.org"
		;;
esac

echo -e "\n  Now APK repo: ${ALPINE_REPO}\n"
sed -ri.$(date "+%F%T") "s/([^/0-9]+\.[a-z]+)/${ALPINE_REPO}/g" /etc/apk/repositories
