#!/bin/env sh

if [ -z $1 ]; then
	_r=${mirror}
else
	_r=$1
fi

case "$_r" in
aliyun)
	ALPINE_REPO="mirrors.aliyun.com"
	;;
ustc)
	ALPINE_REPO="mirrors.ustc.edu.cn"
	;;
tuna)
	ALPINE_REPO="mirror.tuna.tsinghua.edu.cn"
	;;
*)
	ALPINE_REPO="dl-cdn.alpinelinux.org"
	;;
esac

echo -e "\n  Now APK repo: ${ALPINE_REPO}\n"
sed -ri.$(date "+%F%T") "s/([^/0-9]+\.[a-z]+)/${ALPINE_REPO}/g" /etc/apk/repositories
